FROM cli-env

ENV PATH=/node-v22.21.1-linux-x64/bin/:$PATH
USER devuser
WORKDIR /home/devuser
RUN npm install -g cline@1.0.8

USER devuser
COPY --chown=devuser:devuser cursor/.cline /home/devuser/.cline

COPY cursor/cli_server.py /app/
WORKDIR /home/devuser/project

USER root
CMD [ "python3", "/app/cli_server.py" ]

# docker build -t cli-env:cline -f Dockerfile.cline .
